name: K6 Spike Tests

on:
  schedule:
    # Run at 1:30 UTC every day
    - cron: "30 1 * * *"

jobs:
  spike-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript tests
        run: npm run build

      - name: Run k6 tests with Docker
        env:
          INFLUXDB_URL: ${{ secrets.INFLUXDB_URL }}
          INFLUXDB_TOKEN: ${{ secrets.INFLUXDB_TOKEN }}
          INFLUXDB_ORG: ${{ secrets.INFLUXDB_ORG }}
          INFLUXDB_BUCKET: ${{ secrets.INFLUXDB_BUCKET }}
        run: |
          docker run --rm -i -v $(pwd):/app grafana/k6 run --out influxdbv2=$INFLUXDB_URL?org=$INFLUXDB_ORG&bucket=$INFLUXDB_BUCKET&token=$INFLUXDB_TOKEN /app/dist/spike-test.js

      - name: Generate report
        run: node reporter/generate-report.ts

      - name: Upload report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: html-report/report.html

  publish-report:
    runs-on: ubuntu-latest
    needs: spike-tests
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: k6-report

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload report to GitHub Pages
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: your-report-output-directory/
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4              